# Generated by Django 6.0.1 on 2026-02-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_doctorprofile_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorprofile',
            options={'ordering': ['-is_active', '-updated_at'], 'verbose_name': 'Doctor Profile', 'verbose_name_plural': 'Doctor Profiles'},
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
