# Generated by Django 6.0.1 on 2026-01-25 13:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('purpose', models.CharField(choices=[('appointment', 'Appointment'), ('follow_up', 'Follow Up'), ('general', 'General Enquiry')], max_length=20)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('redirected', 'Redirected to WhatsApp'), ('completed', 'Completed')], default='initiated', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_intents', to='appointments.appointment')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['purpose'], name='messaging_m_purpose_fd7844_idx'), models.Index(fields=['created_at'], name='messaging_m_created_1af773_idx')],
            },
        ),
    ]
