# Generated by Django 6.0.1 on 2026-01-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Dr Olaosebikan', max_length=200)),
                ('tagline', models.CharField(max_length=255)),
                ('hero_title', models.CharField(max_length=255)),
                ('hero_subtitle', models.TextField(default='Trusted Medical Care Backed by Research & Experience')),
                ('hero_cta_text', models.CharField(default='Book Appointment', max_length=100)),
                ('hero_cta_link', models.CharField(default='/appointments/book/', max_length=200)),
                ('meta_description', models.TextField(help_text='SEO meta description')),
                ('meta_keywords', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('about', 'About'), ('services', 'Services'), ('contact', 'Contact'), ('privacy', 'Privacy Policy')], max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
