# Generated by Django 6.0.1 on 2026-01-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_alter_staticpage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
