# Generated by Django 6.0.1 on 2026-01-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_staticpage_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
