# Generated by Django 6.0.1 on 2026-02-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_sitesettings_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site Settings', 'verbose_name_plural': 'Site Settings'},
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_name',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='tagline',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='clinic_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='clinic_name',
            field=models.CharField(default='Pain, Arthritis, Autoimmune & Rheumatology Clinic', help_text='Main brand name shown in navbar, footer, titles.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='clinic_tagline',
            field=models.CharField(default='Specialist care for pain, arthritis, autoimmune & rheumatic diseases.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Default OpenGraph image used for link previews.', null=True, upload_to='seo/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_facebook',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_instagram',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_linkedin',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_twitter',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_youtube',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='2348107971507', help_text='International format recommended, e.g. 2348XXXXXXXXXX', max_length=30),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_cta_text',
            field=models.CharField(default='Book an Appointment', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.TextField(default='Evidence-based treatment for arthritis, autoimmune disease, chronic pain and inflammatory conditions — led by Dr Olaosebikan.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(default='Expert Rheumatology Care You Can Trust', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_description',
            field=models.TextField(default='Specialist rheumatology clinic for pain, arthritis, autoimmune and rheumatic diseases. Book an appointment with Dr Olaosebikan.', help_text='Default SEO description (used site-wide unless overridden).'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_keywords',
            field=models.CharField(default='rheumatology, arthritis, autoimmune, pain clinic, joint pain, inflammation, lupus, gout, back pain, rheumatoid arthritis', max_length=400),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
