# Generated by Django 6.0.1 on 2026-02-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_alter_sitesettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.TextField(default='Evidence-based treatment for arthritis, autoimmune disease, chronic pain and inflammatory conditions.'),
        ),
    ]
