# Generated by Django 6.0.1 on 2026-01-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='authors',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='publication',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Mark as featured to highlight this publication.'),
        ),
        migrations.AddField(
            model_name='publication',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Uncheck if the publication is not yet published.'),
        ),
    ]
