# Generated by Django 6.0.1 on 2026-01-26 08:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_publication_authors_publication_is_featured_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['is_featured'], name='publication_is_feat_5c571d_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['year'], name='publication_year_7f8d21_idx'),
        ),
    ]
