# Generated by Django 6.0.1 on 2026-02-10 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_achievement_is_published_achievement_published_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['-year', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-year', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='publication',
            name='publication_year_7f8d21_idx',
        ),
        migrations.AlterField(
            model_name='publication',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='publication',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='slug',
            field=models.SlugField(blank=True, max_length=320),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['doctor', 'year'], name='publication_doctor__d68292_idx'),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['is_published'], name='publication_is_publ_ab1e8b_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['doctor', 'year'], name='publication_doctor__aa16af_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['is_published'], name='publication_is_publ_d7c2b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='publication',
            constraint=models.UniqueConstraint(fields=('doctor', 'slug'), name='unique_publication_slug_per_doctor'),
        ),
    ]
