# Generated by Django 6.0.1 on 2026-01-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='position',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
    ]
