# Generated by Django 6.0.1 on 2026-02-13 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_service_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['position']},
        ),
    ]
