# Generated by Django 6.0.1 on 2026-02-13 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_service_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['position', 'name', 'order']},
        ),
    ]
