# Generated by Django 6.0.1 on 2026-02-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_service_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, default='shield-check', help_text='Icon key (e.g. shield-check, bolt, heart, beaker, hand-raised)', max_length=50),
        ),
    ]
